### ISSUE TITLE
findnodata --debug requires matplotlib

### ISSUE THREAD

**Issue by perrygeo** [mapbox/rio-alpha#27]
Running `test_cli_findnodata_debug_success` fails if you don't install matplotlib first. We should list it as a dependency, possibly a soft "extra" dependency.

```
$ rio findnodata tests/fixtures/fi_all/W4441A.tiny.tif --discovery --debug
...
ImportError: No module named matplotlib.pyplot
```

**Comment by virginiayung** [comment]
Thanks for catching this @perrygeo. I added Matplotlib as an optional runtime dependency here in PR https://github.com/mapbox/rio-alpha/pull/28/commits/ec95f7c3d7e25c05664c2548fb6a333a65844652.
