### ISSUE TITLE
Convert between different nodata representations?

### ISSUE THREAD

**Issue by perrygeo** [mapbox/rio-alpha#30]
In #9, we list a number of different implementations of nodata masks. It would be handy to have a tool to convert between these representations with a CLI. 

As an example, I wrote a [script to convert RGBA tiffs to RGB + internal mask](https://gist.github.com/perrygeo/3dde6210473275fccf7a6d90843b0d4c) - fleshing that out a bit more might be useful. We could do conversions to and from RGBA, RGB + nodata, and RGB + internal/external mask.

`rio-alpha` may or may not be the place for this but putting it here for consideration...

**Comment by jacquestardie** [comment]
I especially like this idea if it means we add some bombproof documentation on the different representations of nodata.  Having it as part of `rio-alpha` makes sense to me.

**Comment by sgillies** [comment]
We've moved on. Will reopen if needed after 1.0.
