### ISSUE TITLE
different ways to represent nodata

### ISSUE THREAD

**Issue by perrygeo** [mapbox/rio-alpha#9]
There are a number of different ways that nodata can be determined. Depending on how generalizable we need to make this tool, we should consider each of these scenarios.
- The dataset has internal `nodata` value set in metadata
- The dataset has an alpha band
- The dataset has an internal binary mask (formats like GTiff allow a mask that is not considered a band)
- The dataset has an external binary mask (a `*.msk` file alongside the main raster)
- The user of the tool supplies the `nodata` value, either as a single value or a list of per-band values. Useful for when the dataset doesn't say anything about it's nodata situation.

The first four can be handled with the new `dataset_masks` method in Rasterio which [normalizes all of these cases](https://github.com/mapbox/rasterio/blob/master/rasterio/_io.pyx#L1145-L1170) into a single 2D array that can serve as an alpha band. 

The case of user-input nodata value would need to be handled separately and would take precedent. Something like:

```
with rasterio.open(raster) as src:
    if user_nodata:
        alpha = get_alpha_mask(..., nodata=user_nodata)
    else:
        alpha = src.dataset_mask()
```
- 
  See also http://mapbox.github.io/rasterio/topics/masks.html#nodata-representations-in-raster-files

**Comment by dnomadb** [comment]
Here's a table describing all the combinations of the above things, and a few things that we should add functionality for; all the "?" should eventually be filled:

NDV in metadata | User-provided NDV | Internal mask | User-provided mask | Geojson mask | BEHAVIOR
--- | --- | --- | --- | --- | ---
X | X | X | X | X | ?
X | X | X | X | - | ?
X | X | X | - | X | ?
X | X | X | - | - | ?
X | X | - | X | X | ?
X | X | - | X | - | ?
X | X | - | - | X | ?
X | X | - | - | - | ?
X | - | X | X | X | ?
X | - | X | X | - | ?
X | - | X | - | X | ?
X | - | X | - | - | ?
X | - | - | X | X | ?
X | - | - | X | - | ?
X | - | - | - | X | ?
X | - | - | - | - | ?
- | X | X | X | X | ?
- | X | X | X | - | ?
- | X | X | - | X | ?
- | X | X | - | - | ?
- | X | - | X | X | ?
- | X | - | X | - | ?
- | X | - | - | X | ?
- | X | - | - | - | ?
- | - | X | X | X | ?
- | - | X | X | - | ?
- | - | X | - | X | ?
- | - | X | - | - | ?
- | - | - | X | X | ?
- | - | - | X | - | ?
- | - | - | - | X | ?
- | - | - | - | - | ?

**Comment by virginiayung** [comment]
I'm taking a first pass at filling out the `behavior` column in the table above ☝️. Thing's I'm unsure of:
  1. all user-provided masks (external mask or geojson mask) and user-provided ndv, should override the internal mask and ndv in metadata.
  2. I've put an `*` when both `User-provided / external mask`, and `Geojson mask` are provided. How about the user choose which one to use with a command like this:

```
> rio alpha SRC_PATH DST_PATH --user-provided external-mask
```
or
```
> rio alpha SRC_PATH DST_PATH --user-provided geojson-mask
```


NDV in metadata | User-provided NDV | Internal mask | User-provided / external mask | Geojson mask | BEHAVIOR
--- | --- | --- | --- | --- | ---
X | X | X | X | X | *
X | X | X | X | - | use external mask
X | X | X | - | X | use geojson mask
X | X | X | - | - | NDV(user)
X | X | - | X | X | *
X | X | - | X | - | use external mask
X | X | - | - | X | use geojson mask
X | X | - | - | - | NDV(user)
X | - | X | X | X | *
X | - | X | X | - | use external mask
X | - | X | - | X | use geojson mask
X | - | X | - | - | use internal mask
X | - | - | X | X | *
X | - | - | X | - | use external mask
X | - | - | - | X | use geojson mask
X | - | - | - | - | NDV(meta)
- | X | X | X | X | *
- | X | X | X | - | * use external mask
- | X | X | - | X | * use geojson mask
- | X | X | - | - | * use NDV(user)
- | X | - | X | X | *
- | X | - | X | - | * use external mask
- | X | - | - | X |* use geojson mask
- | X | - | - | - | use NDV(user)
- | - | X | X | X | *
- | - | X | X | - | * use external mask
- | - | X | - | X | * use geojson mask
- | - | X | - | - | use internal mask
- | - | - | X | X | *
- | - | - | X | - | use external mask 
- | - | - | - | X | use geojson mask
- | - | - | - | - | use mask filled with 255

**Comment by perrygeo** [comment]
I appreciate the detail here but I suspect the logic is a bit simpler:

* if the user provides anything (ndv, ndv array, geojson, mask raster) that takes precedent.
* else use whatever the `src.dataset_mask` says (which handles all those internal cases)

We'd need to enforce that the user only provides one input - if you specify an ndv *and* a geojson *and* a mask raster that should raise a click error since it's ambiguous.

**Comment by dnomadb** [comment]
Of course it can be logically simplified, but I'd just like us to be able to answer each case.

One thing I am concerned about w/ `dataset_mask()` (as noted here: https://github.com/mapbox/rasterio/issues/879) is that it _could_ (as far as I can tell) come from an internal mask, or, from a nodata value - we'll need to sort this out, I think.

**Comment by perrygeo** [comment]
> One thing I am concerned about w/ dataset_mask() (as noted here: mapbox/rasterio#879) is that it could (as far as I can tell) come from an internal mask, or, from a nodata value - we'll need to sort this out, I think.

That's kind of the point - we already have sorted it out with a well defined (and tested) method in Rasterio core that takes the complexities and boils it all down to a 2D alpha mask.

If the user provides something to override the dataset's inherent mask, that's where we can branch the logic. But we don't need to consider this entire matrix of possibilities because, effectively we (and GDAL RFC 15) have already done that work in Rasterio's `dataset_mask`.

**Comment by virginiayung** [comment]
> If the user provides something to override the dataset's inherent mask, that's where we can branch the logic. 
@perrygeo Would you suggest branching off from dataset_mask logic in rasterio or here in rio-alpha?

**Comment by perrygeo** [comment]
Here in `rio alpha`. IOW, rio alpha will give users the ability to override the dataset mask with their own info.

**Comment by sgillies** [comment]
We've moved on. Can reopen this after 1.0 if needed.
